CREATE DATABASE mercearia_herplin;
USE mercearia_herplin;
SELECT * FROM INFORMATION_SCHEMA.TABLES;

CREATE TABLE limpeza (
  id INT NOT NULL IDENTITY PRIMARY KEY,
  nome VARCHAR(80) NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  g_ml INT NOT NULL,
  estoque CHAR(3) CHECK(estoque IN('Sim', 'Não')) NOT NULL DEFAULT 'Não',
  qtd_un INT,
  preco_antigo FLOAT,
  preco_novo FLOAT
);

SELECT * FROM limpeza WHERE tipo = 'Sabão em Pó Caixa' AND g_ml = 400;

INSERT INTO limpeza (nome, tipo, g_ml)
VALUES
  ('Omo Lavagem Perfeita 800g', 'Sabão em Pó Caixa', 800),
  ('Omo Sports 800g', 'Sabão em Pó Caixa', 800),
  ('Tixan Ypê Primavera 1kg', 'Sabão em Pó Caixa', 1000),
  ('Tixan Ypê Maciez 1kg', 'Sabão em Pó Caixa', 1000),
  ('Brilhante Limpeza Total 800g', 'Sabão em Pó Caixa', 800),
  ('Assim Floral 900g', 'Sabão em Pó Caixa', 900),
  ('Assim Poder das Enzimas - Tradicional 900g', 'Sabão em Pó Caixa', 900),
  ('Brilhante Limpeza Total 800g', 'Sabão em Pó Sachê', 800),
  ('Surf 5 em 1 Rosa e Flor de Liz 800g', ' Sabão em Pó Sachê', 800),
  ('Surf Limão e Bicarbonato 800g', ' Sabão em Pó Sachê', 800),
  ('Surf Lavanda 800g', ' Sabão em Pó Sachê', 800),
  ('Surf Cuidado do Coco 800g', ' Sabão em Pó Sachê', 800),
  ('Ares Flores do Campo 1kg', ' Sabão em Pó Sachê', 1000),
  ('Ares Camomila 1kg', ' Sabão em Pó Sachê', 1000),
  ('Ares Lavanda 1kg', ' Sabão em Pó Sachê', 1000),
  ('Omo Lavagem Perfeita 400g', 'Sabão em Pó Caixa', 400),
  ('Tixan Ypê Primavera 500g', 'Sabão em Pó Caixa', 500),
  ('Tixan Ypê Maciez 500g', 'Sabão em Pó Caixa', 500),
  ('Assim Floral 500g', 'Sabão em Pó Caixa', 500),
  ('Assim Poder das Enzimas - Tradicional 500g', 'Sabão em Pó Caixa', 500),
  ('Poliflor Cera Incolor 750ml', 'Cera Líquida', 750),
  ('Poliflor Ardósia 750ml', 'Cera Líquida', 750),
  ('Poliflor Vermelha 750ml', 'Cera Líquida', 750),
  ('Tacolac Super 500ml', 'Cera Líquida', 500),
  ('Brilho Fácil Vermelha 750ml', 'Cera Líquida', 750),
  ('Brilho Fácil Incolor 750ml', 'Cera Líquida', 750),
  ('Brilho Fácil Ardósia 750ml', 'Cera Líquida', 750),
  ('Pasta Multiuso Cristal Rosa 500ml', 'Sabão em Pasta', 500),
  ('Assolan Sabão em Pasta 500ml', 'Sabão em Pasta', 500),
  ('Urca Sabão em Pasta 500ml', 'Sabão em Pasta', 500),
  ('Super 500ml', 'Limpa Alumínio', 500),
  ('Diabo Verde 500ml', 'Limpa Alumínio', 500),
  ('Desentupidor de Pias e Ralos 300g', 'Desentupidor Químico', 300),
  ('Easy-off 250ml', 'Limpa Fornos', 250),
  ('Sapólio Radium Clássico 200g', 'Saponáceo', 200),
  ('Sapólio Radium Multiuso 300g', 'Saponáceo', 300),
  ('Sapólio Radium Multiuso c/ Cloro Ativo 300g', 'Saponáceo', 300),
  ('Sapólio Radium Multiuso c/ Cloro Ativo 250ml', 'Saponáceo', 250),
  ('Sapólio Radium Cremoso Multiuso Lavanda 250ml', 'Saponáceo Cremoso', 250),
  ('Sapólio Radium Cremoso Multiuso Clássico 250ml', 'Saponáceo Cremoso', 250),
  ('Sapólio Radium Cremoso Multiuso Limão 250ml', 'Saponáceo Cremoso', 250),
  ('Cif Multiuso Limão 250ml', 'Limpador Cremoso', 250),
  ('Cif Multiuso Original 250ml', 'Limpador Cremoso', 250),
  ('Veja Limpa Vidros Cristal 500ml', 'Limpa Vidro', 500),
  ('Veja Limpa Vidros Tradicional 500ml', 'Limpa Vidro', 500),
  ('Poliflor Lavanda 200ml', 'Lustra Móveis', 200),
  ('Poliflor Jasmim 200ml', 'Lustra Móveis', 200),
  ('Destac Brilha-Móveis 200ml', 'Lustra Móveis', 200),
  ('Peroba do Campo 200ml', 'Lustra Móveis', 200),
  ('Óleo de Peroba 200ml', 'Lustra Móveis', 200),
  ('Colman Anil Líquido 200ml', 'Corante Líquido', 200),
  ('Colman Anil Imperial 90g', 'Corante em Cubo', 90),
  ('Semorin 50ml', 'Tira Ferrugem', 50),
  ('King Óleo Multiuso 100ml', 'Óleo Multiuso', 100),
  ('Bom Ar Lavando 360ml', 'Aerossol', 360),
  ('Sampa Clean - Limpador Perfumado Concentrado Eucalipto 140ml', 'Limpador Líquido', 140),
  ('Sampa Clean - Limpador Perfumado Concentrado Ubatuba 140ml', 'Limpador Líquido', 140),
  ('Sampa Clean - Limpador Perfumado Concentrado Lavanda 140ml', 'Limpador Líquido', 140),
  ('Harpic Pedra Perfumada Bosque de Pinho 25g', 'Bloco Sanitário', 25),
  ('Harpic Pedra Perfumada Lavanda 25g', 'Bloco Sanitário', 25),
  ('Desumidificador Enxug Comfort 80g', 'Antimofo', 80),
  ('Desumidificador Enxug Talco 80g', 'Antimofo', 80),
  ('Desumidificador Enxug Amora 80g', 'Antimofo', 80),
  ('Antimofo Antitraço (vários), 25g', 'Antimofo', 25),
  ('Saco de Lixo 100L', 'Saco de Lixo', 100000),
  ('Saco de Lixo 50L', 'Saco de Lixo', 50000),
  ('Saco de Lixo 30L', 'Saco de Lixo', 30000),
  ('Saco de Lixo 15L', 'Saco de Lixo', 15000),
  ('Limpol Coco 500ml', 'Detergente', 500),
  ('Limpol Limão 500ml', 'Detergente', 500),
  ('Limpol Maçã 500ml', 'Detergente', 500),
  ('Limpol Neutro 500ml', 'Detergente', 500),
  ('Ypê Coco 500ml', 'Detergente', 500),
  ('Ypê Limão 500ml', 'Detergente', 500),
  ('Ypê Capim-limão 500ml', 'Detergente', 500),
  ('Ypê Maçã 500ml', 'Detergente', 500),
  ('Ypê Neutro 500ml', 'Detergente', 500),
  ('Ypê Clear 500ml', 'Detergente', 500),
  ('Kin Limp Lavanda 1L', 'Removedor', 1000),
  ('Tupi Tradicional 1L', 'Querosene', 1000),
  ('Zumbi 1L', 'Removedor', 1000),
  ('Búfalo Tradicional 1L', 'Querosene', 1000),
  ('Búfalo Tradicional 1L', 'Removedor', 1000),
  ('Zulu Clean s/ Cheiro 900ml', 'Removedor', 900),
  ('Zulu Perfumado 450ml', 'Removedor', 450),
  ('Zulu Clean 450ml', 'Removedor', 450),
  ('Apache 500ml', 'Querosene', 500),
  ('Zumbi 500ml', 'Removedor', 500),
  ('Vimak Floral 500ml', 'Removedor', 500),
  ('Búfalo Tradicional 500ml', 'Querosene', 500),
  ('Búfalo Lavanda 500ml', 'Querosene', 500),
  ('Kin Limp Lavanda 500ml', 'Removedor', 500);

DROP TABLE limpeza